<?php

namespace Database\Seeders;

use App\Models\Autor;
use Illuminate\Database\Seeder;

class AutorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Autor::insert(
            [
                ['nombre' => 'Zsuzsa', 'apellido' => 'Bank'],
                ['nombre' => 'Israel Yehoshua', 'apellido' => 'Singer'],
                ['nombre' => 'Bernd', 'apellido' => 'Brunner'],
                ['nombre' => 'Helen', 'apellido' => 'Oyeyemi'],
                ['nombre' => 'Laura Imai', 'apellido' => 'Messina'],
                ['nombre' => 'Ben', 'apellido' => 'Brooks'],
                ['nombre' => 'Javier', 'apellido' => 'Urra'],
                ['nombre' => 'Miguel', 'apellido' => 'Gane'],
                ['nombre' => 'Thomas', 'apellido' => 'Hardy'],
                ['nombre' => 'Henri Beyle', 'apellido' => 'Stendhal'],
                ['nombre' => 'Ernst T. A.', 'apellido' => 'Hoffmann'],
                ['nombre' => 'Marco Valerio', 'apellido' => 'Marcial'],
                ['nombre' => 'Elizabeth', 'apellido' => 'Barrett Browning'],
                ['nombre' => 'George', 'apellido' => 'Eliot'],
                ['nombre' => 'Rachel', 'apellido' => 'Elliott'],
                ['nombre' => 'Mike', 'apellido' => 'Alfreds'],
                ['nombre' => 'Megan', 'apellido' => 'McDonald'],
                ['nombre' => 'Joyce Carol', 'apellido' => 'Oates'],
                ['nombre' => 'Ona', 'apellido' => 'Carbonell'],
                ['nombre' => 'Karen M.', 'apellido' => 'McManus'],
                ['nombre' => 'Natsume', 'apellido' => 'Soseki'],
                ['nombre' => 'Ken', 'apellido' => 'Liu'],
                ['nombre' => 'Luis', 'apellido' => 'Aguado'],
                ['nombre' => 'Edgar Allan', 'apellido' => 'Poe'],
                ['nombre' => 'Francisco', 'apellido' => 'Hinojosa'],
                ['nombre' => 'Karina', 'apellido' => 'Sosa Castañeda'],
                ['nombre' => 'Jorge', 'apellido' => 'Volpi'],
                ['nombre' => 'Guillermo', 'apellido' => 'Fadanelli'],
                ['nombre' => 'Milena', 'apellido' => 'Busquets'],
                ['nombre' => 'Emmanuel', 'apellido' => 'Carrere'],
                ['nombre' => 'Olga', 'apellido' => 'Tokarczuk'],
                ['nombre' => 'Hunter S.', 'apellido' => 'Thompson'],
                ['nombre' => 'Savannah', 'apellido' => 'Knoop'],
                ['nombre' => 'Graham', 'apellido' => 'Priest'],
                ['nombre' => 'Ruben', 'apellido' => 'Martin G.'],
                ['nombre' => 'Pablo', 'apellido' => 'Natale'],
                ['nombre' => 'Malva', 'apellido' => 'Flores'],
                ['nombre' => 'Sarah', 'apellido' => 'Bakewell'],
                ['nombre' => 'Joaquin M.', 'apellido' => 'Fuster'],
                ['nombre' => 'Claudi', 'apellido' => 'Alsina'],
                ['nombre' => 'Roger', 'apellido' => 'Caillois'],
                ['nombre' => 'Juan', 'apellido' => 'Arnau'],
                ['nombre' => 'Ednodio', 'apellido' => 'Quintero'],
                ['nombre' => 'Nicolas', 'apellido' => 'Gomez Davila'],
                ['nombre' => 'Derek', 'apellido' => 'Jarman'],
                ['nombre' => 'William S.', 'apellido' => 'Burroughs'],
                ['nombre' => 'Franco', 'apellido' => 'Berardi'],
                ['nombre' => 'Jack', 'apellido' => 'Kerouac'],
                ['nombre' => 'William', 'apellido' => 'Blake'],
                ['nombre' => 'Carmen', 'apellido' => 'Laforet'],
                ['nombre' => 'Carlos', 'apellido' => 'Aguilar'],
                ['nombre' => 'Aldous', 'apellido' => 'Huxley'],
                ['nombre' => 'Esquilo', 'apellido' => ''],
                ['nombre' => 'Sofocles', 'apellido' => ''],
                ['nombre' => 'Tito', 'apellido' => 'Livio'],
                ['nombre' => 'Euripides', 'apellido' => ''],
                ['nombre' => 'Aldo', 'apellido' => 'Rossi'],
                ['nombre' => 'Hans Ulrich', 'apellido' => 'Obrist'],
                ['nombre' => 'Miquel', 'apellido' => 'Abellan'],
                ['nombre' => 'Eva', 'apellido' => 'Minguet'],
                ['nombre' => 'Benedetto', 'apellido' => 'Sacareno'],
                ['nombre' => 'Byung-Chul', 'apellido' => 'Han'],
                ['nombre' => 'Giorgo', 'apellido' => 'Nardone'],
                ['nombre' => 'Alberto', 'apellido' => 'Maggi'],
                ['nombre' => 'Yuko', 'apellido' => 'Tsushima'],
                ['nombre' => 'Stanislaw', 'apellido' => 'Lem'],
                ['nombre' => 'Tori', 'apellido' => 'Telfer'],
                ['nombre' => 'Laurel', 'apellido' => 'Snyder'],
                ['nombre' => 'Jaime', 'apellido' => 'Sabines'],
                ['nombre' => 'Agustin', 'apellido' => 'Yañez'],
                ['nombre' => 'Jorge', 'apellido' => 'Ibarguengoitia'],
                ['nombre' => 'Martin Luis', 'apellido' => 'Guzman'],
                ['nombre' => 'San Marcos', 'apellido' => 'Editorial'],
                ['nombre' => 'Norma', 'apellido' => 'Editorial'],
                ['nombre' => 'Adriana', 'apellido' => 'Larrañaga'],
                ['nombre' => 'Gloria Jimena', 'apellido' => 'Durán'],
                ['nombre' => 'Lorena', 'apellido' => 'Cordona Alarcón'],
                ['nombre' => 'Santillana', 'apellido' => 'Editorial'],
                ['nombre' => 'Dennis E.', 'apellido' => 'Showalter'],
                ['nombre' => 'Christian', 'apellido' => 'Hartmann'],
                ['nombre' => 'William', 'apellido' => 'Napier'],
                ['nombre' => 'Rex A.', 'apellido' => 'Wade'],
                ['nombre' => 'George', 'apellido' => 'Washington'],
                ['nombre' => 'Jack', 'apellido' => 'London'],
                ['nombre' => 'Carson', 'apellido' => 'McCullers'],
                ['nombre' => 'Albert', 'apellido' => 'Murray'],
                ['nombre' => 'Colm', 'apellido' => 'Toibin'],
                ['nombre' => 'Lauren', 'apellido' => 'Groff'],
                ['nombre' => 'Pauline', 'apellido' => 'Delabroy-Allard'],
                ['nombre' => 'Edna', 'apellido' => 'OBrien'],
                ['nombre' => 'Charllote', 'apellido' => 'Cory'],
                ['nombre' => 'Isaak', 'apellido' => 'Babel'],
                ['nombre' => 'Aleksandr', 'apellido' => 'Kuprin'],
                ['nombre' => 'Fiodor', 'apellido' => 'Dostoyevski'],
                ['nombre' => 'Henry David', 'apellido' => 'Thoreau'],
                ['nombre' => 'Sara', 'apellido' => 'Boix Llaveria'],
                ['nombre' => 'Edward', 'apellido' => 'Burne-Jones'],
                ['nombre' => 'Pierre', 'apellido' => 'Drieu la Rochelle'],
                ['nombre' => 'Stefan', 'apellido' => 'Zweig'],
                ['nombre' => 'Edward', 'apellido' => 'de Bono'],
                ['nombre' => 'Judy', 'apellido' => 'Wajcman'],
                ['nombre' => 'Rufina', 'apellido' => 'Pearson'],
                ['nombre' => 'Jojo', 'apellido' => 'Moyes'],
                ['nombre' => 'Paul', 'apellido' => 'Auster'],
                ['nombre' => 'Joseph', 'apellido' => 'Campbell'],
                ['nombre' => 'Robert Louis', 'apellido' => 'Stevenson'],
                ['nombre' => 'Massimo', 'apellido' => 'Bottura'],
                ['nombre' => 'Madelaine', 'apellido' => 'Vasquez Galvez'],
                ['nombre' => 'James', 'apellido' => 'Cahill'],
                ['nombre' => 'Rene', 'apellido' => 'Burri'],
                ['nombre' => 'Marianne', 'apellido' => 'Cronin'],
                ['nombre' => 'Eva', 'apellido' => 'Saenz de Urturi'],
                ['nombre' => 'Ana Maria', 'apellido' => 'Shua'],
                ['nombre' => 'Dan', 'apellido' => 'Brown'],
                ['nombre' => 'Julia', 'apellido' => 'Navarro'],
                ['nombre' => 'Robin', 'apellido' => 'Cook'],
                ['nombre' => 'Simona', 'apellido' => 'Ahrnstedt'],
                ['nombre' => 'Juan', 'apellido' => 'Rulfo'],
                ['nombre' => 'Jose', 'apellido' => 'Lebrero Stalss'],
                ['nombre' => 'Lucas', 'apellido' => 'Riera'],
                ['nombre' => 'Kazuma', 'apellido' => 'Obara'],
                ['nombre' => 'Vern E.', 'apellido' => 'Smith'],
                ['nombre' => 'Jean', 'apellido' => 'Malaquais'],
                ['nombre' => 'Dan', 'apellido' => 'Fante'],
                ['nombre' => 'Jenny', 'apellido' => 'Downham'],
                ['nombre' => 'Carlos', 'apellido' => 'Zanon'],
                ['nombre' => 'Jonas', 'apellido' => 'Jonasson'],
                ['nombre' => 'Erin', 'apellido' => 'Hunter'],
                ['nombre' => 'Alex', 'apellido' => 'Pler'],
                ['nombre' => 'Gianni', 'apellido' => 'Simone'],
                ['nombre' => 'A.L.', 'apellido' => 'Sadler'],
                ['nombre' => 'Eiji', 'apellido' => 'Yoshikawa'],
                ['nombre' => 'Elena', 'apellido' => 'Poniatowska'],
                ['nombre' => 'Hans', 'apellido' => 'Fallada'],
                ['nombre' => 'Don', 'apellido' => 'Delillo'],
                ['nombre' => 'Markus', 'apellido' => 'Orths'],
                ['nombre' => 'Pierre', 'apellido' => 'Alferi'],
                ['nombre' => 'Yves', 'apellido' => 'Bonnefoy'],
                ['nombre' => 'Emanuele', 'apellido' => 'Trevi'],
                ['nombre' => 'Omar Robert', 'apellido' => 'Hamilton'],
                ['nombre' => 'Marcos', 'apellido' => 'Roitman Rosenmann'],
                ['nombre' => 'Octavio', 'apellido' => 'Paz'],
                ['nombre' => 'Ulla', 'apellido' => 'Wikander'],
                ['nombre' => 'Mario', 'apellido' => 'Bunge'],
                ['nombre' => 'Benjamin', 'apellido' => 'Moser'],
                ['nombre' => 'Cees', 'apellido' => 'Nooteboom'],
                ['nombre' => 'Natasha', 'apellido' => 'Kaufman'],
                ['nombre' => 'Jostein', 'apellido' => 'Gaarder'],
                ['nombre' => 'Nancy', 'apellido' => 'Jo Sales'],
                ['nombre' => 'Sunil', 'apellido' => 'Sethi'],
                ['nombre' => 'Hajo', 'apellido' => 'Duchting'],
                ['nombre' => 'Yang', 'apellido' => 'Liu'],
                ['nombre' => 'Herbert', 'apellido' => 'Butterfield'],
                ['nombre' => 'Mircea', 'apellido' => 'Eliade'],
                ['nombre' => 'Karl', 'apellido' => 'Kraus'],
                ['nombre' => 'Oscar', 'apellido' => 'Wilde'],
                ['nombre' => 'Soren', 'apellido' => 'Kierkegaard'],
                ['nombre' => 'Luce', 'apellido' => 'Lopez-Baralt'],
                ['nombre' => 'Juan Jose', 'apellido' => 'Tamayo'],
                ['nombre' => 'Charles', 'apellido' => 'Marsh'],
                ['nombre' => 'Banana', 'apellido' => 'Yoshimoto'],
                ['nombre' => 'Gonzalo', 'apellido' => 'Celorio'],
                ['nombre' => 'Leonardo', 'apellido' => 'Padura'],
                ['nombre' => 'Cristina', 'apellido' => 'Fernandez Cuba'],
                ['nombre' => 'Shelby', 'apellido' => 'Mahurin'],
                ['nombre' => 'Julio', 'apellido' => 'Bevione'],
                ['nombre' => 'Johannes', 'apellido' => 'Hinrich von Borstel'],
                ['nombre' => 'Slavica', 'apellido' => 'Bogdanov'],
                ['nombre' => 'Antonio Jose', 'apellido' => 'Navarro'],
                ['nombre' => 'Robert', 'apellido' => 'Chambers'],
                ['nombre' => 'Richard', 'apellido' => 'Burton'],
                ['nombre' => 'Mathew', 'apellido' => 'Lewis'],
                ['nombre' => 'Bruño', 'apellido' => 'Editorial'],
                ['nombre' => 'Nathali', 'apellido' => 'Falcón Vera'],
                ['nombre' => 'Ruben', 'apellido' => 'Alva Cabrera']
            ]
        );
    }
}
