<?php

namespace Database\Seeders;

use App\Models\Libro;
use Illuminate\Database\Seeder;

class LibroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $imagen = 'http://127.0.0.1:8000/images/libros/default-book.png';
        Libro::insert(
            [
                ['titulo' => 'Libro de Actividades Comunica 2° de Primaria', 'titulo_slug' => 'libro-de-actividades-comunica-2-de-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Libro de Actividades Resuelve 1° de Primaria', 'titulo_slug' => 'libro-de-actividades-resuelve-1-de-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Lengua 3° Primaria Saber Hacer', 'titulo_slug' => 'lengua-3-primaria-saber-hacer', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Resuelve 3° de Primaria', 'titulo_slug' => 'texto-escolar-resuelve-3-de-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Comunica 6° de Primaria', 'titulo_slug' => 'texto-escolar-comunica-6-de-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Comunicación 3° de Secundaria ', 'titulo_slug' => 'texto-escolar-comunicacion-3-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Comunicacion 1° de Secundaria', 'titulo_slug' => 'texto-escolar-comunicacion-1-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Comunicacion 2° de Secundaria', 'titulo_slug' => 'texto-escolar-comunicacion-2-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Matemática 2° de Secundaria ', 'titulo_slug' => 'texto-escolar-matematica-2-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia y Tecnología 1° de Secundaria', 'titulo_slug' => 'texto-escolar-ciencia-y-tecnologia-1-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia y Tecnología 2° de Secundaria', 'titulo_slug' => 'texto-escolar-ciencia-y-tecnologia-2-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia Sociales 1° de Secundaria', 'titulo_slug' => 'texto-escolar-ciencia-sociales-1-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia Sociales 2° de Secundaria', 'titulo_slug' => 'texto-escolar-ciencia-sociales-2-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia Sociales 4° de Secundaria ', 'titulo_slug' => 'texto-escolar-ciencia-sociales-4-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Texto Escolar Ciencia Sociales 5° de Secundaria', 'titulo_slug' => 'texto-escolar-ciencia-sociales-5-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Comunicación Construye 1° de Secundaria ', 'titulo_slug' => 'comunicacion-construye-1-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 3],
                ['titulo' => 'Libro de Actividades Construye Ciencia y Tecnología 6° de Primaria', 'titulo_slug' => 'libro-de-actividades-construye-ciencia-y-tecnologia-6-de-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 3],
                ['titulo' => 'Lecturama I Comprensión lectora y producción textual', 'titulo_slug' => 'lecturama-i-comprension-lectora-y-produccion-textual', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 47],
                ['titulo' => 'Lecturama J Comprensión lectora y producción textual', 'titulo_slug' => 'lecturama-j-comprension-lectora-y-produccion-textual', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 47],
                ['titulo' => 'Descubre Matemática 2° de Secundaria', 'titulo_slug' => 'descubre-matematica-2-de-secundaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 3],
                ['titulo' => 'Diccionario Didáctico Ilustrado', 'titulo_slug' => 'diccionario-didactico-ilustrado', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 3],
                ['titulo' => 'Compendio de Lengua', 'titulo_slug' => 'compendio-de-lengua', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Compendio de Literatura', 'titulo_slug' => 'compendio-de-literatura', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Compendio de Álgebra', 'titulo_slug' => 'compendio-de-algebra', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Compendio de Geometría', 'titulo_slug' => 'compendio-de-geometria', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Compendio de Química', 'titulo_slug' => 'compendio-de-quimica', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Compendio de Geografía', 'titulo_slug' => 'compendio-de-geografia', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Cuando los Inviernos eran Inviernos', 'titulo_slug' => 'cuando-los-inviernos-eran-inviernos', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 5],
                ['titulo' => 'De un mundo que ya no esta', 'titulo_slug' => 'de-un-mundo-que-ya-no-esta', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 5],
                ['titulo' => 'Los días luminosos', 'titulo_slug' => 'los-dias-luminosos', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 5],
                ['titulo' => 'Ahora que ya bailas', 'titulo_slug' => 'ahora-que-ya-bailas', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 6],
                ['titulo' => 'Lo que no es tuyo no es tuyo', 'titulo_slug' => 'lo-que-no-es-tuyo-no-es-tuyo', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 5],
                ['titulo' => 'Cuentos para niños que se atreven a ser diferentes', 'titulo_slug' => 'cuentos-para-ninos-que-se-atreven-a-ser-diferentes', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 6],
                ['titulo' => '¿Quién es quien?', 'titulo_slug' => 'quien-es-quien', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 6],
                ['titulo' => 'WA La vía japonesa de la armonía', 'titulo_slug' => 'wa-la-via-japonesa-de-la-armonia', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 6],
                ['titulo' => 'Lejos del mundanal ruido', 'titulo_slug' => 'lejos-del-mundanal-ruido', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 10],
                ['titulo' => 'Cuentos de música y músicos', 'titulo_slug' => 'cuentos-de-musica-y-musicos', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 10],
                ['titulo' => 'Epigramas', 'titulo_slug' => 'epigramas', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 10],
                ['titulo' => 'Kandinsky', 'titulo_slug' => 'kandinsky', 'anyo_de_lanzamiento' => 2015, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 42],
                ['titulo' => 'Rojo y negro', 'titulo_slug' => 'rojo-y-negro', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 10],
                ['titulo' => 'Aurora Leigh', 'titulo_slug' => 'aurora-leigh', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 11],
                ['titulo' => 'Diferente cada noche', 'titulo_slug' => 'diferente-cada-noche', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 11],
                ['titulo' => 'El molino de Floss', 'titulo_slug' => 'el-molino-de-floss', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 11],
                ['titulo' => 'No dar de comer al oso', 'titulo_slug' => 'no-dar-de-comer-al-oso', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 11],
                ['titulo' => 'Alguien es el siguiente', 'titulo_slug' => 'alguien-es-el-siguiente', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 12],
                ['titulo' => 'DELATORA', 'titulo_slug' => 'delatora', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 12],
                ['titulo' => 'Elena Sirena Sueños de Agua', 'titulo_slug' => 'elena-sirena-suenos-de-agua', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 12],
                ['titulo' => 'Judy Moody es experta en libros', 'titulo_slug' => 'judy-moody-es-experta-en-libros', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 12],
                ['titulo' => 'Cuando la mente encontró a su cerebro', 'titulo_slug' => 'cuando-la-mente-encontro-a-su-cerebro', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 7],
                ['titulo' => 'Cuentos imprescindibles', 'titulo_slug' => 'cuentos-imprescindibles', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 7],
                ['titulo' => 'Estrellas rotas', 'titulo_slug' => 'estrellas-rotas', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 7],
                ['titulo' => 'Soy un gato', 'titulo_slug' => 'soy-un-gato', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 7],
                ['titulo' => 'Caballo fantasma', 'titulo_slug' => 'caballo-fantasma', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 13],
                ['titulo' => 'Las agujas dementes', 'titulo_slug' => 'las-agujas-dementes', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 13],
                ['titulo' => 'Lodo', 'titulo_slug' => 'lodo', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 13],
                ['titulo' => 'Migraña en racimos', 'titulo_slug' => 'migrana-en-racimos', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 13],
                ['titulo' => 'Chica, Chico, Chica', 'titulo_slug' => 'chica-chico-chica', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 15],
                ['titulo' => 'Thomas Pynchon un escritor sin orificios', 'titulo_slug' => 'thomas-pynchon-un-escritor-sin-orificios', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 15],
                ['titulo' => 'Un oso polar', 'titulo_slug' => 'un-oso-polar', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 15],
                ['titulo' => 'Uno', 'titulo_slug' => 'uno', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 15],
                ['titulo' => 'Gema', 'titulo_slug' => 'gema', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 14],
                ['titulo' => 'Miedo y asco en Las Vegas', 'titulo_slug' => 'miedo-y-asco-en-las-vegas', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 14],
                ['titulo' => 'Un lugar llamado antaño', 'titulo_slug' => 'un-lugar-llamado-antano', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 14],
                ['titulo' => 'Yoga', 'titulo_slug' => 'yoga', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 14],
                ['titulo' => 'Cerebro y libertad', 'titulo_slug' => 'cerebro-y-libertad', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 16],
                ['titulo' => 'En el café de los existencialistas', 'titulo_slug' => 'en-el-cafe-de-los-existencialistas', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 16],
                ['titulo' => 'Estrella de dos puntas', 'titulo_slug' => 'estrella-de-dos-puntas', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 16],
                ['titulo' => 'Vitaminas matemáticas', 'titulo_slug' => 'vitaminas-matematicas', 'anyo_de_lanzamiento' => 2008, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 16],
                ['titulo' => 'Breviario de escolios', 'titulo_slug' => 'breviario-de-escolios', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 17],
                ['titulo' => 'Cuentos salvajes', 'titulo_slug' => 'cuentos-salvajes', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 17],
                ['titulo' => 'Poder del sueño', 'titulo_slug' => 'poder-del-sueno', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 17],
                ['titulo' => 'Upanisad', 'titulo_slug' => 'upanisad', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 17],
                ['titulo' => 'Croma', 'titulo_slug' => 'croma', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 18],
                ['titulo' => 'Futurabilidad', 'titulo_slug' => 'futurabilidad', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 18],
                ['titulo' => 'Revolución electrónica', 'titulo_slug' => 'revolucion-electronica', 'anyo_de_lanzamiento' => 2009, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 18],
                ['titulo' => 'Viajero solitario', 'titulo_slug' => 'viajero-solitario', 'anyo_de_lanzamiento' => 2013, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 18],
                ['titulo' => 'Augurios de inocencia', 'titulo_slug' => 'augurios-de-inocencia', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 19],
                ['titulo' => 'Guía del cine', 'titulo_slug' => 'guia-del-cine', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 19],
                ['titulo' => 'Mono y esencia', 'titulo_slug' => 'mono-y-esencia', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 19],
                ['titulo' => 'Nada', 'titulo_slug' => 'nada', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 19],
                ['titulo' => 'Antigona', 'titulo_slug' => 'antigona', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 8],
                ['titulo' => 'Fenicias', 'titulo_slug' => 'fenicias', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 8],
                ['titulo' => 'Historia de roma desde su fundación', 'titulo_slug' => 'historia-de-roma-desde-su-fundacion', 'anyo_de_lanzamiento' => 2006, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 8],
                ['titulo' => 'Las Coéforas', 'titulo_slug' => 'las-coeforas', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 8],
                ['titulo' => 'Ai Weiwei', 'titulo_slug' => 'ai-weiwei', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 20],
                ['titulo' => 'Eat Drink Graphics', 'titulo_slug' => 'eat-drink-graphics', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 20],
                ['titulo' => 'Posicionamientos', 'titulo_slug' => 'posicionamientos', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 20],
                ['titulo' => 'Hotel brand identity', 'titulo_slug' => 'hotel-brand-identity', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 20],
                ['titulo' => 'Caras de la muerte', 'titulo_slug' => 'caras-de-la-muerte', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 21],
                ['titulo' => 'Emociones', 'titulo_slug' => 'emociones', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 21],
                ['titulo' => 'Nuestra señora de los herejes', 'titulo_slug' => 'nuestra-senora-de-los-herejes', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 21],
                ['titulo' => 'Sobre la pobreza de la psiquiatría', 'titulo_slug' => 'sobre-la-pobreza-de-la-psiquiatria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 21],
                ['titulo' => 'Charlie y Raton', 'titulo_slug' => 'charlie-y-raton', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 22],
                ['titulo' => 'Damas asesinas', 'titulo_slug' => 'damas-asesinas', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 22],
                ['titulo' => 'Provocación', 'titulo_slug' => 'provocacion', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 22],
                ['titulo' => 'Territorio de luz', 'titulo_slug' => 'territorio-de-luz', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 22],
                ['titulo' => 'Algo sobre la muerte del mayor Sabines', 'titulo_slug' => 'algo-sobre-la-muerte-del-mayor-sabines', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 23],
                ['titulo' => 'Estas ruinas que ves', 'titulo_slug' => 'estas-ruinas-que-ves', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 23],
                ['titulo' => 'Javier Mina', 'titulo_slug' => 'javier-mina', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 23],
                ['titulo' => 'Los Sentidos al aire', 'titulo_slug' => 'los-sentidos-al-aire', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 23],
                ['titulo' => '1917', 'titulo_slug' => '1917', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 24],
                ['titulo' => 'Choque de imperios', 'titulo_slug' => 'choque-de-imperios', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 24],
                ['titulo' => 'La Batalla de Kursk', 'titulo_slug' => 'la-batalla-de-kursk', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 24],
                ['titulo' => 'Operación Barbarroja', 'titulo_slug' => 'operacion-barbarroja', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 24],
                ['titulo' => 'Carson McCullers', 'titulo_slug' => 'carson-mccullers', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 25],
                ['titulo' => 'Collected essays & memoirs', 'titulo_slug' => 'collected-essays-memoirs', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 25],
                ['titulo' => 'The Call of the wild', 'titulo_slug' => 'the-call-of-the-wild', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 25],
                ['titulo' => 'Writings', 'titulo_slug' => 'writings', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 25],
                ['titulo' => 'Florida', 'titulo_slug' => 'florida', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 26],
                ['titulo' => 'La Chica', 'titulo_slug' => 'la-chica', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 26],
                ['titulo' => 'Madres e hijos', 'titulo_slug' => 'madres-e-hijos', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 26],
                ['titulo' => 'Voy a hablar de Sarah', 'titulo_slug' => 'voy-a-hablar-de-sarah', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 26],
                ['titulo' => 'Armonía celestial', 'titulo_slug' => 'armonia-celestial', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 28],
                ['titulo' => 'Cuentos de Odesa', 'titulo_slug' => 'cuentos-de-odesa', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 27],
                ['titulo' => 'El Duelo', 'titulo_slug' => 'el-duelo', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 27],
                ['titulo' => 'El Jugador', 'titulo_slug' => 'el-jugador', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 27],
                ['titulo' => 'Los que no perdonan', 'titulo_slug' => 'los-que-no-perdonan', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 27],
                ['titulo' => 'El Agente doble', 'titulo_slug' => 'el-agente-doble', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 28],
                ['titulo' => 'Libro de flores', 'titulo_slug' => 'libro-de-flores', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 28],
                ['titulo' => 'Noche y luz de luna', 'titulo_slug' => 'noche-y-luz-de-luna', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 28],
                ['titulo' => 'Balzac', 'titulo_slug' => 'balzac', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 29],
                ['titulo' => 'Dislexia', 'titulo_slug' => 'dislexia', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 29],
                ['titulo' => 'Esclavos del tiempo', 'titulo_slug' => 'esclavos-del-tiempo', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 29],
                ['titulo' => 'Seis pares de zapatos para la acción', 'titulo_slug' => 'seis-pares-de-zapatos-para-la-accion', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 29],
                ['titulo' => 'City of Glass', 'titulo_slug' => 'city-of-glass', 'anyo_de_lanzamiento' => 2009, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 30],
                ['titulo' => 'After You', 'titulo_slug' => 'after-you', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 30],
                ['titulo' => 'Creative Mythology', 'titulo_slug' => 'creative-mythology', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 30],
                ['titulo' => 'Treasure Island', 'titulo_slug' => 'treasure-island', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 30],
                ['titulo' => 'Cuba', 'titulo_slug' => 'cuba', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 31],
                ['titulo' => 'El Pan es oro', 'titulo_slug' => 'el-pan-es-oro', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 31],
                ['titulo' => 'Impossible Reminiscences', 'titulo_slug' => 'impossible-reminiscences', 'anyo_de_lanzamiento' => 2013, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 31],
                ['titulo' => 'Volar demasiado cerca del cielo', 'titulo_slug' => 'volar-demasiado-cerca-del-cielo', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 31],
                ['titulo' => 'Aquitania', 'titulo_slug' => 'aquitania', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 32],
                ['titulo' => 'El Valiente y la bella', 'titulo_slug' => 'el-valiente-y-la-bella', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 32],
                ['titulo' => 'Inferno', 'titulo_slug' => 'inferno', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 32],
                ['titulo' => 'Los Cien años de Lenni y Margot', 'titulo_slug' => 'los-cien-anos-de-lenni-y-margot', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 32],
                ['titulo' => 'Dispara, yo ya estoy muerto', 'titulo_slug' => 'dispara-yo-ya-estoy-muerto', 'anyo_de_lanzamiento' => 2013, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 33],
                ['titulo' => 'Infección', 'titulo_slug' => 'infeccion', 'anyo_de_lanzamiento' => 2015, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 33],
                ['titulo' => 'Solo esta noche', 'titulo_slug' => 'solo-esta-noche', 'anyo_de_lanzamiento' => 2013, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 33],
                ['titulo' => 'Tu no mataras', 'titulo_slug' => 'tu-no-mataras', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 33],
                ['titulo' => 'El Gallo de oro y otros relatos', 'titulo_slug' => 'el-gallo-de-oro-y-otros-relatos', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 34],
                ['titulo' => 'Exposure', 'titulo_slug' => 'exposure', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 34],
                ['titulo' => 'Extintos', 'titulo_slug' => 'extintos', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 34],
                ['titulo' => 'Prohibido el cante', 'titulo_slug' => 'prohibido-el-cante', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 34],
                ['titulo' => 'Chump change', 'titulo_slug' => 'chump-change', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 35],
                ['titulo' => 'Fante', 'titulo_slug' => 'fante', 'anyo_de_lanzamiento' => 2013, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 35],
                ['titulo' => 'Los Reyes del jaco', 'titulo_slug' => 'los-reyes-del-jaco', 'anyo_de_lanzamiento' => 2015, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 35],
                ['titulo' => 'Sin visado', 'titulo_slug' => 'sin-visado', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 35],
                ['titulo' => 'Antes de morirme', 'titulo_slug' => 'antes-de-morirme', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 36],
                ['titulo' => 'Atardecer(Los Gatos Guerreros | La Nueva Profecía 6)', 'titulo_slug' => 'atardecer-los-gatos-guerreros-la-nueva-profecia-6', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 36],
                ['titulo' => 'El Abuelo que volvió para salvar el mundo', 'titulo_slug' => 'el-abuelo-que-volvio-para-salvar-el-mundo', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 36],
                ['titulo' => 'Tarde, mal y nunca', 'titulo_slug' => 'tarde-mal-y-nunca', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 36],
                ['titulo' => 'El Cantar de Heike', 'titulo_slug' => 'el-cantar-de-heike', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 37],
                ['titulo' => 'Hanakotoba', 'titulo_slug' => 'hanakotoba', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 37],
                ['titulo' => 'Shogun', 'titulo_slug' => 'shogun', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 37],
                ['titulo' => 'Tokio la guía geek', 'titulo_slug' => 'tokio-la-guia-geek', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 37],
                ['titulo' => 'Body Art', 'titulo_slug' => 'body-art', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 38],
                ['titulo' => 'En mi país desconocido', 'titulo_slug' => 'en-mi-pais-desconocido', 'anyo_de_lanzamiento' => 2012, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 38],
                ['titulo' => 'Encierro que arde', 'titulo_slug' => 'encierro-que-arde', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 38],
                ['titulo' => 'La Camarera', 'titulo_slug' => 'la-camarera', 'anyo_de_lanzamiento' => 2010, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 38],
                ['titulo' => 'Algo escrito', 'titulo_slug' => 'algo-escrito', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 39],
                ['titulo' => 'El Camino familiar del pez combativo', 'titulo_slug' => 'el-camino-familiar-del-pez-combativo', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 39],
                ['titulo' => 'Juntos todavia', 'titulo_slug' => 'juntos-todavia', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 39],
                ['titulo' => 'Ciudad siempre gana', 'titulo_slug' => 'ciudad-siempre-gana', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 39],
                ['titulo' => 'De criada a empleada', 'titulo_slug' => 'de-criada-a-empleada', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 40],
                ['titulo' => 'Economia y filosofia', 'titulo_slug' => 'economia-y-filosofia', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 40],
                ['titulo' => 'Por la razón o la fuerza', 'titulo_slug' => 'por-la-razon-o-la-fuerza', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 40],
                ['titulo' => 'Posdata', 'titulo_slug' => 'posdata', 'anyo_de_lanzamiento' => 2017, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 40],
                ['titulo' => 'Meditación para estudiantes', 'titulo_slug' => 'meditacion-para-estudiantes', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 41],
                ['titulo' => 'Por que este mundo', 'titulo_slug' => 'por-que-este-mundo', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 41],
                ['titulo' => 'Simplemente perfecto', 'titulo_slug' => 'simplemente-perfecto', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 41],
                ['titulo' => 'Venecia', 'titulo_slug' => 'venecia', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 41],
                ['titulo' => 'Amy Winehouse Blake wood', 'titulo_slug' => 'amy-winehouse-blake-wood', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 42],
                ['titulo' => 'Hombre y mujer cara a cara', 'titulo_slug' => 'hombre-y-mujer-cara-a-cara', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 42],
                ['titulo' => 'Living in Asia Vol. 1', 'titulo_slug' => 'living-in-asia-vol-1', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 42],
                ['titulo' => 'Contra los periodistas y otros contras', 'titulo_slug' => 'contra-los-periodistas-y-otros-contras', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 9],
                ['titulo' => 'La Decadencia de la mentira y otros ensayos', 'titulo_slug' => 'la-decadencia-de-la-mentira-y-otros-ensayos', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 9],
                ['titulo' => 'Las Promesas del equinoccio', 'titulo_slug' => 'las-promesas-del-equinoccio', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 9],
                ['titulo' => 'Los Orígenes de la ciencia moderna', 'titulo_slug' => 'los-origenes-de-la-ciencia-moderna', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 9],
                ['titulo' => 'El libro sobre Adler', 'titulo_slug' => 'el-libro-sobre-adler', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 43],
                ['titulo' => 'Extraña gloria', 'titulo_slug' => 'extrana-gloria', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 43],
                ['titulo' => 'Hermano Islam', 'titulo_slug' => 'hermano-islam', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 43],
                ['titulo' => 'La Cima del éxtasis', 'titulo_slug' => 'la-cima-del-extasis', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 43],
                ['titulo' => 'Del esplendor de la lengua española', 'titulo_slug' => 'del-esplendor-de-la-lengua-espanola', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 44],
                ['titulo' => 'La Habitación de Nona', 'titulo_slug' => 'la-habitacion-de-nona', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 44],
                ['titulo' => 'Lagartija', 'titulo_slug' => 'lagartija', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 44],
                ['titulo' => 'Mascaras', 'titulo_slug' => 'mascaras', 'anyo_de_lanzamiento' => 2016, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 44],
                ['titulo' => 'Aprender a gestionar el tiempo fácilmente', 'titulo_slug' => 'aprender-a-gestionar-el-tiempo-facilmente', 'anyo_de_lanzamiento' => 2018, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 45],
                ['titulo' => 'Asesino de brujas', 'titulo_slug' => 'asesino-de-brujas', 'anyo_de_lanzamiento' => 2021, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 45],
                ['titulo' => 'El Corazón', 'titulo_slug' => 'el-corazon', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 45],
                ['titulo' => 'Volver a mi', 'titulo_slug' => 'volver-a-mi', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 45],
                ['titulo' => 'El Monje', 'titulo_slug' => 'el-monje', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 46],
                ['titulo' => 'El Rey de Amarillo', 'titulo_slug' => 'el-rey-de-amarillo', 'anyo_de_lanzamiento' => 2014, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 46],
                ['titulo' => 'La Maldición de la momia', 'titulo_slug' => 'la-maldicion-de-la-momia', 'anyo_de_lanzamiento' => 2015, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 46],
                ['titulo' => 'Las Montañas de la Luna', 'titulo_slug' => 'las-montanas-de-la-luna', 'anyo_de_lanzamiento' => 2011, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 46],
                ['titulo' => 'Matemática 1 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-1-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Matemática 2 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-2-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Matemática 3 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-3-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Matemática 4 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-4-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Matemática 5 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-5-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Matemática 6 - Crecemos Juntos Primaria', 'titulo_slug' => 'matematica-6-crecemos-juntos-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 1],
                ['titulo' => 'Comunicación 1 - Primaria', 'titulo_slug' => 'comunicacion-1-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Comunicación 2 - Primaria', 'titulo_slug' => 'comunicacion-2-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Comunicación 3 - Primaria', 'titulo_slug' => 'comunicacion-3-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Comunicación 4 - Primaria', 'titulo_slug' => 'comunicacion-4-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Comunicación 5 - Primaria', 'titulo_slug' => 'comunicacion-5-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Comunicación 6 - Primaria', 'titulo_slug' => 'comunicacion-6-primaria', 'anyo_de_lanzamiento' => 2020, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 2],
                ['titulo' => 'Razonamiento Verbal Siglo XXI', 'titulo_slug' => 'razonamiento-verbal-siglo-xxi', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4],
                ['titulo' => 'Trigonometría Uniciencia Sapiens', 'titulo_slug' => 'trigonometria-uniciencia-sapiens', 'anyo_de_lanzamiento' => 2019, 'imagen' => $imagen, 'idioma_id' => 1, 'editorial_id' => 4]
            ]
        );
    }
}
