<?php

namespace Database\Seeders;

use App\Models\SubClasificacion;
use Illuminate\Database\Seeder;

class SubClasificacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SubClasificacion::insert(
            [
                ['sub_clasificacion' => 'Conocimiento', 'codigo_dewey' => '001', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'El libro', 'codigo_dewey' => '002', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'Sistemas', 'codigo_dewey' => '003', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'Procesamiento de datos, Ciencia de los computadores', 'codigo_dewey' => '004', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'Programación, programas, datos de computador', 'codigo_dewey' => '005', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'Métodos especiales de computador', 'codigo_dewey' => '006', 'clasificacion_id' => 1],
                ['sub_clasificacion' => 'Bibliografías', 'codigo_dewey' => '011', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'Bibliografías de individuos', 'codigo_dewey' => '012', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'De obras por categorías específicas de autores', 'codigo_dewey' => '013', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'De obras anónimas y seudónimas', 'codigo_dewey' => '014', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'De obras de lugares específicos', 'codigo_dewey' => '015', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'De obras sobre temas específicos', 'codigo_dewey' => '016', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'Catálogos generales por materia', 'codigo_dewey' => '017', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'Catálogos ordenados por autor, fecha, etc.', 'codigo_dewey' => '018', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'Catálogos diccionario', 'codigo_dewey' => '019', 'clasificacion_id' => 2],
                ['sub_clasificacion' => 'Relaciones bibliotecarias', 'codigo_dewey' => '021', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Administracion de la planta física', 'codigo_dewey' => '022', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Administración de personal', 'codigo_dewey' => '023', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Operaciones bibliotecarias', 'codigo_dewey' => '025', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Bibliotecas para temas específicos', 'codigo_dewey' => '026', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Bibliotecas generales', 'codigo_dewey' => '027', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Lectura y uso de otros medios de información', 'codigo_dewey' => '028', 'clasificacion_id' => 3],
                ['sub_clasificacion' => 'Lengua inglesa norteamericana', 'codigo_dewey' => '031', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En inglés', 'codigo_dewey' => '032', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En otras lenguas germánicas', 'codigo_dewey' => '033', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En francés, provenzal, catalán', 'codigo_dewey' => '034', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En italiano, rumano, retorromano', 'codigo_dewey' => '035', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En español y portugués', 'codigo_dewey' => '036', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En lenguas eslavas', 'codigo_dewey' => '037', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En lenguas escandinavas', 'codigo_dewey' => '038', 'clasificacion_id' => 4],
                ['sub_clasificacion' => 'En otras lenguas', 'codigo_dewey' => '039', 'clasificacion_id' => 4],
                ['sub_clasificacion' => '(no asignado)', 'codigo_dewey' => '041', 'clasificacion_id' => 5],
                ['sub_clasificacion' => 'Lengua inglesa norteamericana', 'codigo_dewey' => '051', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En inglés', 'codigo_dewey' => '052', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En otra lenguas germánicas', 'codigo_dewey' => '053', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En francés , provenzal, catalán', 'codigo_dewey' => '054', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En italiano, rumano, retorromano', 'codigo_dewey' => '055', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En español y portugués', 'codigo_dewey' => '056', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En lenguas eslavas', 'codigo_dewey' => '057', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En lenguas escandinavas', 'codigo_dewey' => '058', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En otras lenguas', 'codigo_dewey' => '059', 'clasificacion_id' => 6],
                ['sub_clasificacion' => 'En América del Norte', 'codigo_dewey' => '061', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En las Islas Británicas En Inglaterra.', 'codigo_dewey' => '062', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En Europa Central En Alemania', 'codigo_dewey' => '063', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En Francía y Mónaco', 'codigo_dewey' => '064', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En Italia y territorios adyacentes', 'codigo_dewey' => '065', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En la Península Ibérica e islas adyacentes', 'codigo_dewey' => '066', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En Europa Oriental En Rusia', 'codigo_dewey' => '067', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'En otras áreas geográficas', 'codigo_dewey' => '068', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'Museología (Ciencia de los Museos)', 'codigo_dewey' => '069', 'clasificacion_id' => 7],
                ['sub_clasificacion' => 'Periodismo y periódicos en América del Norte', 'codigo_dewey' => '071', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En las Islas Británicas. En Inglaterra', 'codigo_dewey' => '072', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Europa Central. En Alemania', 'codigo_dewey' => '073', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Francía y Mónaco', 'codigo_dewey' => '074', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Italia y territorios adyacentes', 'codigo_dewey' => '075', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Península Ibérica e islas adyacentes', 'codigo_dewey' => '076', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Europa Oriental. En Rusia', 'codigo_dewey' => '077', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En Escandinavia', 'codigo_dewey' => '078', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'En otras áreas geográficas', 'codigo_dewey' => '079', 'clasificacion_id' => 8],
                ['sub_clasificacion' => 'Lengua inglesa norteamericana', 'codigo_dewey' => '081', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'Colecciones generales en inglés', 'codigo_dewey' => '082', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En otras lenguas germánicas', 'codigo_dewey' => '083', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En francés, provenzal, catalán', 'codigo_dewey' => '084', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En italiano, rumano, retorromano', 'codigo_dewey' => '085', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En español y portugués', 'codigo_dewey' => '086', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En lenguas eslavas', 'codigo_dewey' => '087', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En lenguas escandinavas', 'codigo_dewey' => '088', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'En lenguas itálicas, helénicas, otras lenguas', 'codigo_dewey' => '089', 'clasificacion_id' => 9],
                ['sub_clasificacion' => 'Manuscritos', 'codigo_dewey' => '091', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros xilográficos', 'codigo_dewey' => '092', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Incunables', 'codigo_dewey' => '093', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros impresos', 'codigo_dewey' => '094', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros notables por su encuadernación', 'codigo_dewey' => '095', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros notables por las ilustraciones', 'codigo_dewey' => '096', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros notables por su propietario u origen', 'codigo_dewey' => '097', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Obras prohibidas, falsificaciones, imposturas', 'codigo_dewey' => '098', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Libros notables por su formato', 'codigo_dewey' => '099', 'clasificacion_id' => 10],
                ['sub_clasificacion' => 'Teoría de la filosofía', 'codigo_dewey' => '101', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '102', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '103', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '105', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Organizaciones y gerencia', 'codigo_dewey' => '106', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '107', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Tratamiento de clases de personas', 'codigo_dewey' => '108', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Tratamiento histórico y colectivo de personas', 'codigo_dewey' => '109', 'clasificacion_id' => 11],
                ['sub_clasificacion' => 'Ontología', 'codigo_dewey' => '111', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Cosmología (Filosofía de la naturaleza)', 'codigo_dewey' => '113', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Espacio', 'codigo_dewey' => '114', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Tiempo', 'codigo_dewey' => '115', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Cambio', 'codigo_dewey' => '116', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Estructura', 'codigo_dewey' => '117', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Fuerza y energía', 'codigo_dewey' => '118', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Número y cantidad', 'codigo_dewey' => '119', 'clasificacion_id' => 12],
                ['sub_clasificacion' => 'Epistemología (Teorìa del conocimiento)', 'codigo_dewey' => '121', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Causalidad', 'codigo_dewey' => '122', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Determinismo e indeterminismo', 'codigo_dewey' => '123', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Teleología', 'codigo_dewey' => '124', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'El yo', 'codigo_dewey' => '126', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'El inconsciente y el subconsciente', 'codigo_dewey' => '127', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Género humano', 'codigo_dewey' => '128', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Origen y destino de las almas individuales', 'codigo_dewey' => '129', 'clasificacion_id' => 13],
                ['sub_clasificacion' => 'Métodos parapsicológicos y ocultos', 'codigo_dewey' => '131', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Parapsicología y ocultismo', 'codigo_dewey' => '133', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Sueños y misterios', 'codigo_dewey' => '135', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Grafología adivinatoria', 'codigo_dewey' => '137', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Fisionomía', 'codigo_dewey' => '138', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Frenología', 'codigo_dewey' => '139', 'clasificacion_id' => 14],
                ['sub_clasificacion' => 'Idealismo y sistemas relacionados', 'codigo_dewey' => '141', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Filosofía crítica', 'codigo_dewey' => '142', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Bergsonìsmo e intuicionismo', 'codigo_dewey' => '143', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Humanismo y sistemas relacionados', 'codigo_dewey' => '144', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Sensacionalismo', 'codigo_dewey' => '145', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Naturalismo y sistemas relacionados', 'codigo_dewey' => '146', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Panteísmo y sistemas relacionados', 'codigo_dewey' => '147', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Eclecticismo, liberalismo, Tradicionalismo', 'codigo_dewey' => '148', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Otros sistemas filosóficos', 'codigo_dewey' => '149', 'clasificacion_id' => 15],
                ['sub_clasificacion' => 'Percepción,movimiento emociones, impulsos', 'codigo_dewey' => '152', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Procesos mentales e inteligencia', 'codigo_dewey' => '153', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Subconsciente y estados alterados', 'codigo_dewey' => '154', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Psicología diferencial y del desarrollo', 'codigo_dewey' => '155', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Psicología comparada', 'codigo_dewey' => '156', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Psicología aplicada', 'codigo_dewey' => '158', 'clasificacion_id' => 16],
                ['sub_clasificacion' => 'Inducción', 'codigo_dewey' => '161', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Deducción', 'codigo_dewey' => '162', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Falacias y fuentes de error', 'codigo_dewey' => '165', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Silogismos', 'codigo_dewey' => '166', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Hipótesis', 'codigo_dewey' => '167', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Argumento y persuasión', 'codigo_dewey' => '168', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Analogía', 'codigo_dewey' => '169', 'clasificacion_id' => 17],
                ['sub_clasificacion' => 'Sistemas éticos', 'codigo_dewey' => '171', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética política', 'codigo_dewey' => '172', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética de las relaciones familiares', 'codigo_dewey' => '173', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética ocupacional', 'codigo_dewey' => '174', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética de la recreación y del tiempo libre', 'codigo_dewey' => '175', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética del sexo y la reproducción', 'codigo_dewey' => '176', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética de las relaciones sociales', 'codigo_dewey' => '177', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Ética del consumo', 'codigo_dewey' => '178', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Otras normas éticas', 'codigo_dewey' => '179', 'clasificacion_id' => 18],
                ['sub_clasificacion' => 'Filosofía oriental', 'codigo_dewey' => '181', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofías griegas presocráticas', 'codigo_dewey' => '182', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofías sofista y socrática', 'codigo_dewey' => '183', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía platónica', 'codigo_dewey' => '184', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía aristotélica', 'codigo_dewey' => '185', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía escéptica y neoplatónica', 'codigo_dewey' => '186', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía epicúrea', 'codigo_dewey' => '187', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía estoica', 'codigo_dewey' => '188', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía medieval occidental', 'codigo_dewey' => '189', 'clasificacion_id' => 19],
                ['sub_clasificacion' => 'Filosofía de Estados Unidos y Canadá', 'codigo_dewey' => '191', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de las Islas Británicas', 'codigo_dewey' => '192', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de Alemania y Austria', 'codigo_dewey' => '193', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de Francia', 'codigo_dewey' => '194', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de Italia', 'codigo_dewey' => '195', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de España y Portugal', 'codigo_dewey' => '196', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de la anterior Unión Soviética', 'codigo_dewey' => '197', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de Escandinavia', 'codigo_dewey' => '198', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Filosofía de otras áreas geográficas', 'codigo_dewey' => '199', 'clasificacion_id' => 20],
                ['sub_clasificacion' => 'Subdivisiones comunes de la religión', 'codigo_dewey' => '201', 'clasificacion_id' => 21],
                ['sub_clasificacion' => 'Conceptos de Dios', 'codigo_dewey' => '211', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Existencia, sapiencia, atributos de Dios.', 'codigo_dewey' => '212', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Creación', 'codigo_dewey' => '213', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Teodicea', 'codigo_dewey' => '214', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Ciencia y Religión', 'codigo_dewey' => '215', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Género humano', 'codigo_dewey' => '218', 'clasificacion_id' => 22],
                ['sub_clasificacion' => 'Antiguo Testamento (Tanakh)', 'codigo_dewey' => '221', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Libros históricos del Antiguo Testamento', 'codigo_dewey' => '222', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Libros poéticos del Antiguo Testamento', 'codigo_dewey' => '223', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Libros proféticos del Antiguo Testamento', 'codigo_dewey' => '224', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Nuevo Testamento', 'codigo_dewey' => '225', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Evangelios y Hechos de los Apóstoles', 'codigo_dewey' => '226', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Epístolas', 'codigo_dewey' => '227', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Revelación (Apocalipsis)', 'codigo_dewey' => '228', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Apócrifos y seudoepígrafes', 'codigo_dewey' => '229', 'clasificacion_id' => 23],
                ['sub_clasificacion' => 'Dios', 'codigo_dewey' => '231', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Jesucristo y su familia', 'codigo_dewey' => '232', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Género humano', 'codigo_dewey' => '233', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Salvación (soteriología y gracia)', 'codigo_dewey' => '234', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Seres espirituales', 'codigo_dewey' => '235', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Escatología', 'codigo_dewey' => '236', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Credos y catecismos', 'codigo_dewey' => '238', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Apologética y polémicas', 'codigo_dewey' => '239', 'clasificacion_id' => 24],
                ['sub_clasificacion' => 'Teología moral', 'codigo_dewey' => '241', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Literatura piadosa', 'codigo_dewey' => '242', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Escritos evangelizadores para individuos', 'codigo_dewey' => '243', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Uso del arte en el cristianismo', 'codigo_dewey' => '246', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Mobiliario y artículos eclesiásticos', 'codigo_dewey' => '247', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Experiencia, práctica, vida cristianas', 'codigo_dewey' => '248', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Observancias cristianas en la vida familiar', 'codigo_dewey' => '249', 'clasificacion_id' => 25],
                ['sub_clasificacion' => 'Predicación (Homilética)', 'codigo_dewey' => '251', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Textos de sermones', 'codigo_dewey' => '252', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Oficio pastoral (Teología pastoral)', 'codigo_dewey' => '253', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Administración de la parroquia', 'codigo_dewey' => '254', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Congregaciones y órdenes religiosas', 'codigo_dewey' => '255', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Atención pastoral de familias y de personas', 'codigo_dewey' => '259', 'clasificacion_id' => 26],
                ['sub_clasificacion' => 'Teología social', 'codigo_dewey' => '261', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Eclesiología', 'codigo_dewey' => '262', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Días, épocas, lugares de observancia', 'codigo_dewey' => '263', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Culto público', 'codigo_dewey' => '264', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Sacramentos, otros ritos y ritos', 'codigo_dewey' => '265', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Misiones', 'codigo_dewey' => '266', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Asociaciones para trabajo religioso', 'codigo_dewey' => '267', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Educación religiosa', 'codigo_dewey' => '268', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Renovación espiritual', 'codigo_dewey' => '269', 'clasificacion_id' => 27],
                ['sub_clasificacion' => 'Órdenes religiosas en la historia de la iglesia', 'codigo_dewey' => '271', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Persecuciones en la historia de la iglesia', 'codigo_dewey' => '272', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Controversias y herejías doctrinales', 'codigo_dewey' => '273', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en Europa', 'codigo_dewey' => '274', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en Asia', 'codigo_dewey' => '275', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en África', 'codigo_dewey' => '276', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en América del Norte', 'codigo_dewey' => '277', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en América del Sur', 'codigo_dewey' => '278', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Historia del cristianismo en otras áreas', 'codigo_dewey' => '279', 'clasificacion_id' => 28],
                ['sub_clasificacion' => 'Iglesia temprana e iglesias orientales', 'codigo_dewey' => '281', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Iglesia Católica Romana', 'codigo_dewey' => '282', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Iglesias anglicanas', 'codigo_dewey' => '283', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Protestantes de origen continental', 'codigo_dewey' => '284', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Iglesias presbiterianas, reformadas, congregacionales', 'codigo_dewey' => '285', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Iglesias bautistas, de los Discípulos de Cristo, adventistas', 'codigo_dewey' => '286', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Iglesias metodistas y relacionadas', 'codigo_dewey' => '287', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Otras confesiones y sectas', 'codigo_dewey' => '289', 'clasificacion_id' => 29],
                ['sub_clasificacion' => 'Religión comparada', 'codigo_dewey' => '291', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Religión clásica (griega y romana)', 'codigo_dewey' => '292', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Religión germánica', 'codigo_dewey' => '293', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Religiones de origen índico', 'codigo_dewey' => '294', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Zoroastrismo (Mazdeísmo, parsismo)', 'codigo_dewey' => '295', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Judaísmo', 'codigo_dewey' => '296', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Islamismo, babismo,fe bahai', 'codigo_dewey' => '297', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Otras religiones', 'codigo_dewey' => '299', 'clasificacion_id' => 30],
                ['sub_clasificacion' => 'Sociología y antropología', 'codigo_dewey' => '301', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Interacción social', 'codigo_dewey' => '302', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Procesos sociales', 'codigo_dewey' => '303', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Factores que afectan el comportamiento social', 'codigo_dewey' => '304', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Grupos sociales', 'codigo_dewey' => '305', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Cultura e instituciones', 'codigo_dewey' => '306', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Comunidades', 'codigo_dewey' => '307', 'clasificacion_id' => 31],
                ['sub_clasificacion' => 'Estadísticas generales de Europa', 'codigo_dewey' => '314', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Estadísticas generales de Asia', 'codigo_dewey' => '315', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Estadísticas generales de África', 'codigo_dewey' => '316', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Estadísticas generales de América del Norte', 'codigo_dewey' => '317', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Estadísticas generales de América del Sur', 'codigo_dewey' => '318', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Estadísticas generales de otras áreas', 'codigo_dewey' => '319', 'clasificacion_id' => 32],
                ['sub_clasificacion' => 'Sistemas de gobiernos y de estados', 'codigo_dewey' => '321', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Relación del estado con grupos organizados', 'codigo_dewey' => '322', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Derechos civiles y políticos', 'codigo_dewey' => '323', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'El proceso político', 'codigo_dewey' => '324', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Migración y colonización internacionales', 'codigo_dewey' => '325', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Esclavitud y emancipación', 'codigo_dewey' => '326', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Relaciones internacionales', 'codigo_dewey' => '327', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'El proceso legislativo', 'codigo_dewey' => '328', 'clasificacion_id' => 33],
                ['sub_clasificacion' => 'Economía laboral', 'codigo_dewey' => '331', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Economía financiera', 'codigo_dewey' => '332', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Economía de la tierra y de la energía', 'codigo_dewey' => '333', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Cooperativas', 'codigo_dewey' => '334', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Socialismo y sistemas relacionados', 'codigo_dewey' => '335', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Finanzas públicas', 'codigo_dewey' => '336', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Economía internacional', 'codigo_dewey' => '337', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Producción', 'codigo_dewey' => '338', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Macroeconomía y temas relacionados', 'codigo_dewey' => '339', 'clasificacion_id' => 34],
                ['sub_clasificacion' => 'Derecho internacional', 'codigo_dewey' => '341', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho constitucional y administrativo', 'codigo_dewey' => '342', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho militar, tributario, mercantil, industrial', 'codigo_dewey' => '343', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho laboral, social , educativo, cultural', 'codigo_dewey' => '344', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho penal', 'codigo_dewey' => '345', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho privado', 'codigo_dewey' => '346', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Procedimiento y tribunales civiles', 'codigo_dewey' => '347', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Leyes (Estatutos), reglamentaciones, jurisprudencia', 'codigo_dewey' => '348', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Derecho de jurisdicciones y áreas específicas', 'codigo_dewey' => '349', 'clasificacion_id' => 35],
                ['sub_clasificacion' => 'Administración pública', 'codigo_dewey' => '351', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Consideraciones generales', 'codigo_dewey' => '352', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Campos específicos de administración pública', 'codigo_dewey' => '353', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Administración de la economía y del medio ambiente', 'codigo_dewey' => '354', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Ciencia militar', 'codigo_dewey' => '355', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Fuerzas y combate de infantería', 'codigo_dewey' => '356', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Fuerzas y combate montados', 'codigo_dewey' => '357', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Fuerzas aéreas y otras fuerzas especializadas', 'codigo_dewey' => '358', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Fuerzas y combate marítimos (navales)', 'codigo_dewey' => '359', 'clasificacion_id' => 36],
                ['sub_clasificacion' => 'Problemas y bienestar sociales en general', 'codigo_dewey' => '361', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Problemas y servicios de bienestar social', 'codigo_dewey' => '362', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Otros problemas y servicios sociales', 'codigo_dewey' => '363', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Criminología', 'codigo_dewey' => '364', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Instituciones penales y relacionadas', 'codigo_dewey' => '365', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Asociaciones', 'codigo_dewey' => '366', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Clubes de carácter general', 'codigo_dewey' => '367', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Seguros', 'codigo_dewey' => '368', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Clases varias de asociaciones', 'codigo_dewey' => '369', 'clasificacion_id' => 37],
                ['sub_clasificacion' => 'Escuelas y actividades; educación especial', 'codigo_dewey' => '371', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Educación primaria', 'codigo_dewey' => '372', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Educación secundaria', 'codigo_dewey' => '373', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Educación de adultos', 'codigo_dewey' => '374', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Currículos', 'codigo_dewey' => '375', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Educación superior', 'codigo_dewey' => '378', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Asuntos de política pública en educación', 'codigo_dewey' => '379', 'clasificacion_id' => 38],
                ['sub_clasificacion' => 'Comercio interno (Comercio doméstico)', 'codigo_dewey' => '381', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Comercio internacional (Comercio exterior)', 'codigo_dewey' => '382', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Comunicación postal', 'codigo_dewey' => '383', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Comunicaciones. Telecomunicación', 'codigo_dewey' => '384', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Transporte ferroviario', 'codigo_dewey' => '385', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Transporte por vía acuática interior y en transbordador', 'codigo_dewey' => '386', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Transporte acuático , aéreo, espacial', 'codigo_dewey' => '387', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Transporte. Transporte terrestre', 'codigo_dewey' => '388', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Metrología y estandarización', 'codigo_dewey' => '389', 'clasificacion_id' => 39],
                ['sub_clasificacion' => 'Traje y apariencia personal', 'codigo_dewey' => '391', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Costumbres del ciclo de vida y de la vida doméstica', 'codigo_dewey' => '392', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Costumbres mortuorias', 'codigo_dewey' => '393', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Costumbres generales', 'codigo_dewey' => '394', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Etiquetas (Modales)', 'codigo_dewey' => '395', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Folclore', 'codigo_dewey' => '398', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Costumbres de guerra y diplomática', 'codigo_dewey' => '399', 'clasificacion_id' => 40],
                ['sub_clasificacion' => 'Filosofía y teoría', 'codigo_dewey' => '401', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '402', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '403', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Temas especiales', 'codigo_dewey' => '404', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '405', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Organizaciones y gerencia', 'codigo_dewey' => '406', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Educación, investigacion, temas relacionados', 'codigo_dewey' => '407', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Tratamiento de clases de personas', 'codigo_dewey' => '408', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Tratamiento geográfico y de personas', 'codigo_dewey' => '409', 'clasificacion_id' => 41],
                ['sub_clasificacion' => 'Sistemas de escritura', 'codigo_dewey' => '411', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Etimología', 'codigo_dewey' => '412', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Diccionarios', 'codigo_dewey' => '413', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Fonología y fonética', 'codigo_dewey' => '414', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Gramática', 'codigo_dewey' => '415', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Dialectología y lingüística histórica', 'codigo_dewey' => '417', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Uso estándar Lingüística aplicada', 'codigo_dewey' => '418', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Lenguaje verbal no hablado ni escrito', 'codigo_dewey' => '419', 'clasificacion_id' => 42],
                ['sub_clasificacion' => 'Sistemas de escritura y fonología ingleses', 'codigo_dewey' => '421', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Etimología inglesa', 'codigo_dewey' => '422', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Diccionarios de inglés', 'codigo_dewey' => '423', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Gramática inglesa', 'codigo_dewey' => '425', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Variaciones de la lengua inglesa', 'codigo_dewey' => '427', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Uso del inglés estándar', 'codigo_dewey' => '428', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Inglés antigüo (Anglosajón)', 'codigo_dewey' => '429', 'clasificacion_id' => 43],
                ['sub_clasificacion' => 'Sistemas de escritura y fonología alemanes', 'codigo_dewey' => '431', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Etimología alemana', 'codigo_dewey' => '432', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Diccionarios de alemán', 'codigo_dewey' => '433', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Gramática alemana', 'codigo_dewey' => '435', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Variaciones de la lengua alemana', 'codigo_dewey' => '437', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Uso del alemán estándar', 'codigo_dewey' => '438', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Otras lenguas germánicas', 'codigo_dewey' => '439', 'clasificacion_id' => 44],
                ['sub_clasificacion' => 'Sistemas de escritura y fonología franceses', 'codigo_dewey' => '441', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Etimología francesa', 'codigo_dewey' => '442', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Diccionarios de francés', 'codigo_dewey' => '443', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Gramática francesa', 'codigo_dewey' => '445', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Variaciones de la lengua francesa', 'codigo_dewey' => '447', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Uso del francés estándar', 'codigo_dewey' => '448', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Provenzal y catalán', 'codigo_dewey' => '449', 'clasificacion_id' => 45],
                ['sub_clasificacion' => 'Sistema de escritura y fonología italianos', 'codigo_dewey' => '451', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Etimología italiana', 'codigo_dewey' => '452', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Diccionario de italiano', 'codigo_dewey' => '453', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Gramática italiana', 'codigo_dewey' => '455', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Variaciones de la lengua italiana', 'codigo_dewey' => '457', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Uso del italiano estándar', 'codigo_dewey' => '458', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Rumano y retorromano', 'codigo_dewey' => '459', 'clasificacion_id' => 46],
                ['sub_clasificacion' => 'Sistemas de escritura y fonología españoles', 'codigo_dewey' => '461', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Etimología española', 'codigo_dewey' => '462', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Diccionario de español', 'codigo_dewey' => '463', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Gramática española', 'codigo_dewey' => '465', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Variaciones de la lengua española', 'codigo_dewey' => '467', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Uso del español estándar', 'codigo_dewey' => '468', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Portugués', 'codigo_dewey' => '469', 'clasificacion_id' => 47],
                ['sub_clasificacion' => 'Escritura y fonología latinas clásicas', 'codigo_dewey' => '471', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Etimología latina clásica', 'codigo_dewey' => '472', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Diccionarios de latín clásico', 'codigo_dewey' => '473', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Gramática latina clásica', 'codigo_dewey' => '475', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Latín antiguo, posclásico, vulgar', 'codigo_dewey' => '477', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Uso del latín clásico', 'codigo_dewey' => '478', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Otras lenguas itálicas', 'codigo_dewey' => '479', 'clasificacion_id' => 48],
                ['sub_clasificacion' => 'Escritura y fonología griegas clásicas', 'codigo_dewey' => '481', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Etimología griega clásica', 'codigo_dewey' => '482', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Diccionarios de griego clásico', 'codigo_dewey' => '483', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Gramática griega clásica', 'codigo_dewey' => '485', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Griego preclásico y posclásico', 'codigo_dewey' => '487', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Uso del griego clásico', 'codigo_dewey' => '488', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Otras lenguas helénicas', 'codigo_dewey' => '489', 'clasificacion_id' => 49],
                ['sub_clasificacion' => 'Lenguas indoeuropeas orientales y célticas', 'codigo_dewey' => '491', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas afroasiáticas. Semíticas', 'codigo_dewey' => '492', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas afroasiáticas no semíticas', 'codigo_dewey' => '493', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas altaicas, urálicas, hiperbóreas, dravídicas', 'codigo_dewey' => '494', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas del Asia oriental y sudoriental', 'codigo_dewey' => '495', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas africanas', 'codigo_dewey' => '496', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas nativas norteamericanas', 'codigo_dewey' => '497', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas nativas sudamericanas', 'codigo_dewey' => '498', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Lenguas austronesias y otras', 'codigo_dewey' => '499', 'clasificacion_id' => 50],
                ['sub_clasificacion' => 'Filosofía y teoría', 'codigo_dewey' => '501', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '502', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '503', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '505', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Organización y gerencia', 'codigo_dewey' => '506', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '507', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Historia natural', 'codigo_dewey' => '508', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Tratamiento histórico , geográfico , de personas', 'codigo_dewey' => '509', 'clasificacion_id' => 51],
                ['sub_clasificacion' => 'Principios generales de las matemáticas', 'codigo_dewey' => '511', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Álgebra, teoría de los números', 'codigo_dewey' => '512', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Aritmética', 'codigo_dewey' => '513', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Topología', 'codigo_dewey' => '514', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Análisis', 'codigo_dewey' => '515', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Geometría', 'codigo_dewey' => '516', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Probabilidades y matemáticas aplicadas', 'codigo_dewey' => '519', 'clasificacion_id' => 52],
                ['sub_clasificacion' => 'Mecánica celeste', 'codigo_dewey' => '521', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Técnicas , equipo, materiales', 'codigo_dewey' => '522', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Cuerpos y fenómenos celestes específicos', 'codigo_dewey' => '523', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'La tierrra (Geografía astronómica)', 'codigo_dewey' => '525', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Geografía matemática', 'codigo_dewey' => '526', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Navegación celeste', 'codigo_dewey' => '527', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Efemérides', 'codigo_dewey' => '528', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Cronología', 'codigo_dewey' => '529', 'clasificacion_id' => 53],
                ['sub_clasificacion' => 'Mecánica clásica. Mecánica de sólidos', 'codigo_dewey' => '531', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Mecánica de fluidos. Mecánica de líquidos', 'codigo_dewey' => '532', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Neumática (Mecánica de gases)', 'codigo_dewey' => '533', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Sonido y vibraciones relacionadas', 'codigo_dewey' => '534', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Luz y fenómenos parafóticos', 'codigo_dewey' => '535', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Calor', 'codigo_dewey' => '536', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Electricidad y electrónica', 'codigo_dewey' => '537', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Magnetismo', 'codigo_dewey' => '538', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Física moderna', 'codigo_dewey' => '539', 'clasificacion_id' => 54],
                ['sub_clasificacion' => 'Química física y teórica', 'codigo_dewey' => '541', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Técnicas, equipo, materiales', 'codigo_dewey' => '542', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Química analítica', 'codigo_dewey' => '543', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Análisis cualitativo', 'codigo_dewey' => '544', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Análisis cuantitativo', 'codigo_dewey' => '545', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Química inorgánica', 'codigo_dewey' => '546', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Química orgánica', 'codigo_dewey' => '547', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Cristalografía', 'codigo_dewey' => '548', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Mineralogía', 'codigo_dewey' => '549', 'clasificacion_id' => 55],
                ['sub_clasificacion' => 'Geología, hidrología, meteorología', 'codigo_dewey' => '551', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Petrología', 'codigo_dewey' => '552', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Geología económica', 'codigo_dewey' => '553', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de Europa', 'codigo_dewey' => '554', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de Asia', 'codigo_dewey' => '555', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de África', 'codigo_dewey' => '556', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de América del Norte', 'codigo_dewey' => '557', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de América del Sur', 'codigo_dewey' => '558', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Ciencias de la tierra de otras áreas', 'codigo_dewey' => '559', 'clasificacion_id' => 56],
                ['sub_clasificacion' => 'Paleobotánica; microorganismos fósiles', 'codigo_dewey' => '561', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Invertebrados fósiles', 'codigo_dewey' => '562', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Otros invertebrados fósiles', 'codigo_dewey' => '563', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Mollusca (Moluscos) y Molluscoidea (Moluscoideos) fósiles', 'codigo_dewey' => '564', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Arthropoda (Artrópodos) fósiles', 'codigo_dewey' => '565', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Chordata (Cordados) fósiles', 'codigo_dewey' => '566', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Vertebrados fósiles de sangre fría', 'codigo_dewey' => '567', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Aves (Pájaros) fósiles', 'codigo_dewey' => '568', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Mammalia (Mamíferos) fósiles', 'codigo_dewey' => '569', 'clasificacion_id' => 57],
                ['sub_clasificacion' => 'Fisiología y temas relacionados', 'codigo_dewey' => '571', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Bioquímica', 'codigo_dewey' => '572', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Sistemas específicos en animales', 'codigo_dewey' => '573', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Partes específicas de y sistemas en plantas', 'codigo_dewey' => '575', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Genética y evolución', 'codigo_dewey' => '576', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Ecología', 'codigo_dewey' => '577', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Historia natural de los organismos', 'codigo_dewey' => '578', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Microorganismos, hongos, algas', 'codigo_dewey' => '579', 'clasificacion_id' => 58],
                ['sub_clasificacion' => 'Temas específicos en historia natural', 'codigo_dewey' => '581', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Plantas destacadas por características y flores', 'codigo_dewey' => '582', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Magnoliosida (Dicotiledóneas)', 'codigo_dewey' => '583', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Liliopsida (Monocotiledóneas)', 'codigo_dewey' => '584', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Pinophyta (Gimnospermas). Coniferales (Coníferas)', 'codigo_dewey' => '585', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Cryptogamia (Criptógamas, Plantas sin semillas)', 'codigo_dewey' => '586', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Pteridophyta (Pteridofitas, Plantas vasculares sin semillas)', 'codigo_dewey' => '587', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Bryophyta (Briofitas)', 'codigo_dewey' => '588', 'clasificacion_id' => 59],
                ['sub_clasificacion' => 'Temas específicos en historia natural', 'codigo_dewey' => '591', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Invertebrados', 'codigo_dewey' => '592', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Invertebrados marinos y del litoral', 'codigo_dewey' => '593', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Mollusca (Moluscos) y Molluscoidea (Moluscoideos)', 'codigo_dewey' => '594', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Arthropoda (Artrópodos)', 'codigo_dewey' => '595', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Chordata (Cordados)', 'codigo_dewey' => '596', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Vertebrados de sangre fría. Pisces (Peces)', 'codigo_dewey' => '597', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Aves (Pájaros)', 'codigo_dewey' => '598', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Mammalia (Mamíferos)', 'codigo_dewey' => '599', 'clasificacion_id' => 60],
                ['sub_clasificacion' => 'Filosofía y teoría', 'codigo_dewey' => '601', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '602', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '603', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Temas especiales', 'codigo_dewey' => '604', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '605', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Organizaciones', 'codigo_dewey' => '606', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '607', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Invenciones y patentes', 'codigo_dewey' => '608', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Tratamiento histórico, geográfico de personas', 'codigo_dewey' => '609', 'clasificacion_id' => 61],
                ['sub_clasificacion' => 'Anatomía humana, citología, histología', 'codigo_dewey' => '611', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Fisiología humana', 'codigo_dewey' => '612', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Promoción de la salud', 'codigo_dewey' => '613', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Incidencia y prevención de la enfermedad', 'codigo_dewey' => '614', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Farmacología y terapéutica', 'codigo_dewey' => '615', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Enfermedades', 'codigo_dewey' => '616', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Cirugía y especialidades médicas relacionadas', 'codigo_dewey' => '617', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Ginecología y otras especialidades médicas', 'codigo_dewey' => '618', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Medicína experimental', 'codigo_dewey' => '619', 'clasificacion_id' => 62],
                ['sub_clasificacion' => 'Física aplicada', 'codigo_dewey' => '621', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Minería y operaciones relacionadas', 'codigo_dewey' => '622', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Ingeniería militar y náutica', 'codigo_dewey' => '623', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Ingeniería civil', 'codigo_dewey' => '624', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Ingeniería de ferrocarriles y de carretera', 'codigo_dewey' => '625', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Ingeniería hidráulica', 'codigo_dewey' => '627', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Ingeniería sanitaria y municipal', 'codigo_dewey' => '628', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Otras ramas de la ingeniería', 'codigo_dewey' => '629', 'clasificacion_id' => 63],
                ['sub_clasificacion' => 'Técnicas, equipo, materiales', 'codigo_dewey' => '631', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Lesiones, enfermedades, plagas vegetales', 'codigo_dewey' => '632', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Cultivos de campo y de plantación', 'codigo_dewey' => '633', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Huertos, frutas, silvicultura', 'codigo_dewey' => '634', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Cultívos hortículas (Horticultura)', 'codigo_dewey' => '635', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Producción animal (Zootecnia)', 'codigo_dewey' => '636', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Procesamiento lechero y productos relacionados', 'codigo_dewey' => '637', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Cultivo de insectos', 'codigo_dewey' => '638', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Caza, pesca, conservación', 'codigo_dewey' => '639', 'clasificacion_id' => 64],
                ['sub_clasificacion' => 'Alimentos y bebidas', 'codigo_dewey' => '641', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Comidas y servicios a la mesa', 'codigo_dewey' => '642', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Vivienda y equipo de la casa', 'codigo_dewey' => '643', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Servicios de la casa', 'codigo_dewey' => '644', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Dotaciones de la casa', 'codigo_dewey' => '645', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Costura, vestuario, vida personal', 'codigo_dewey' => '646', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Gerencia de viviendas públicas', 'codigo_dewey' => '647', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Cuidado de la casa', 'codigo_dewey' => '648', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Crianza de niños y atención domiciliaria de personas', 'codigo_dewey' => '649', 'clasificacion_id' => 65],
                ['sub_clasificacion' => 'Servicios de oficina', 'codigo_dewey' => '651', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Procesos de comunicación escrita', 'codigo_dewey' => '652', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Taquigrafía', 'codigo_dewey' => '653', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Contabilidad', 'codigo_dewey' => '657', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Gerencia general', 'codigo_dewey' => '658', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Publicidad', 'codigo_dewey' => '659', 'clasificacion_id' => 66],
                ['sub_clasificacion' => 'Tecnología de químicos industriales', 'codigo_dewey' => '661', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Explosivos, combustibles, productos relacionados', 'codigo_dewey' => '662', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Tecnología de bebidas', 'codigo_dewey' => '663', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Tecnología de alimentos', 'codigo_dewey' => '664', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Aceites, grasas, ceras, gases industriales', 'codigo_dewey' => '665', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Cerámica y tecnologías afines', 'codigo_dewey' => '666', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Tecnología de la limpieza, del color, del revestimiento', 'codigo_dewey' => '667', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Tecnología de otros productos orgánicos', 'codigo_dewey' => '668', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Metalurgia', 'codigo_dewey' => '669', 'clasificacion_id' => 67],
                ['sub_clasificacion' => 'Metalistería y productos metálicos', 'codigo_dewey' => '671', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Hierro, acero, otras aleaciones ferrosas', 'codigo_dewey' => '672', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Metales no ferrosos', 'codigo_dewey' => '673', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Procesamiento de madera aserrada,productos de madera, corchos', 'codigo_dewey' => '674', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Procesamiento del cuero y de la piel', 'codigo_dewey' => '675', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Tecnología de la pulpa y del papel', 'codigo_dewey' => '676', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Textiles', 'codigo_dewey' => '677', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Elastómeros y productos elastoméricos', 'codigo_dewey' => '678', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Otros productos de materiales específicos', 'codigo_dewey' => '679', 'clasificacion_id' => 68],
                ['sub_clasificacion' => 'Instrumentos de precisión y otros dispositivos', 'codigo_dewey' => '681', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Trabajo de forja pequeña (Herrería)', 'codigo_dewey' => '682', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Ferretería y aparatos de la casa', 'codigo_dewey' => '683', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Muebles y talleres de hogar', 'codigo_dewey' => '684', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Artículos de cuero, de piel, productos relacionados', 'codigo_dewey' => '685', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Imprenta y actividades relacionadas', 'codigo_dewey' => '686', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Vestuario y accesorios', 'codigo_dewey' => '687', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Otros productos acabados y empaques', 'codigo_dewey' => '688', 'clasificacion_id' => 69],
                ['sub_clasificacion' => 'Materiales de construcción', 'codigo_dewey' => '691', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Prácticas auxiliares de construcción', 'codigo_dewey' => '692', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Materiales y propósitos específicos', 'codigo_dewey' => '693', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Construcción en madera Carpintería', 'codigo_dewey' => '694', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Cubiertas para techos', 'codigo_dewey' => '695', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Servicios públicos', 'codigo_dewey' => '696', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Calefacción, ventilación, aire acondicionado', 'codigo_dewey' => '697', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Acabado detallado', 'codigo_dewey' => '698', 'clasificacion_id' => 70],
                ['sub_clasificacion' => 'Filosofía de las bellas artes y artes decorativas', 'codigo_dewey' => '701', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Miscelánea de las bellas artes y artes decorativas', 'codigo_dewey' => '702', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Diccionarios de las bellas artes y artes decorativas', 'codigo_dewey' => '703', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Temas especiales de las bellas artes y artes decorativas', 'codigo_dewey' => '704', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Publicaciones seriadas de las bellas artes y artes decorativas', 'codigo_dewey' => '705', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Organizaciones y gerencia', 'codigo_dewey' => '706', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '707', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Galerías, museos, colecciones privadas', 'codigo_dewey' => '708', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Tratamiento histórico, geográfico, de personas', 'codigo_dewey' => '709', 'clasificacion_id' => 71],
                ['sub_clasificacion' => 'Planificación del espacio (Urbanismo)', 'codigo_dewey' => '711', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Arquitectura paisajística', 'codigo_dewey' => '712', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Arquitectura paisajística de las vías de tráfico', 'codigo_dewey' => '713', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Elementos acuáticos', 'codigo_dewey' => '714', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Plantas leñosas', 'codigo_dewey' => '715', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Plantas herbáceas', 'codigo_dewey' => '716', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Estructuras en arquitectura paisajística', 'codigo_dewey' => '717', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Diseño paisajístico de cementerios', 'codigo_dewey' => '718', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Paisajes naturales', 'codigo_dewey' => '719', 'clasificacion_id' => 72],
                ['sub_clasificacion' => 'Estructura arquitectónica', 'codigo_dewey' => '721', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Arquitectura hasta ca. 300', 'codigo_dewey' => '722', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Arquitectura desde ca. 300 hasta 1399', 'codigo_dewey' => '723', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Arquitectura desde 1400', 'codigo_dewey' => '724', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Estructuras públicas', 'codigo_dewey' => '725', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Edificios para propósitos religiosos', 'codigo_dewey' => '726', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Edificios para educación e investigación', 'codigo_dewey' => '727', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Edificios residenciales y relacionados', 'codigo_dewey' => '728', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Diseño y decoración', 'codigo_dewey' => '729', 'clasificacion_id' => 73],
                ['sub_clasificacion' => 'Procesos, formas, temas de la escultura', 'codigo_dewey' => '731', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Escultura hasta ca. 500', 'codigo_dewey' => '732', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Escultura griega, etrusca, romana', 'codigo_dewey' => '733', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Escultura desde ca. 500 hasta 1399', 'codigo_dewey' => '734', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Escultura desde 1400', 'codigo_dewey' => '735', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Talla y tallados', 'codigo_dewey' => '736', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Numismática y sigilografía', 'codigo_dewey' => '737', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Artes cerámicas', 'codigo_dewey' => '738', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Metalistería artística', 'codigo_dewey' => '739', 'clasificacion_id' => 74],
                ['sub_clasificacion' => 'Dibujo y dibujos', 'codigo_dewey' => '741', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Perspectiva', 'codigo_dewey' => '742', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Dibujo y dibujos por tema', 'codigo_dewey' => '743', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Artes decorativas', 'codigo_dewey' => '745', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Artes textiles', 'codigo_dewey' => '746', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Decoración de interiores', 'codigo_dewey' => '747', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Vidrio', 'codigo_dewey' => '748', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Muebles y accesorios', 'codigo_dewey' => '749', 'clasificacion_id' => 75],
                ['sub_clasificacion' => 'Técnicas, equipo, materiales, formas', 'codigo_dewey' => '751', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Color', 'codigo_dewey' => '752', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Simbolismo, alegoría, mitología, leyenda', 'codigo_dewey' => '753', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Pintura de género', 'codigo_dewey' => '754', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Religión', 'codigo_dewey' => '755', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Figuras humanas', 'codigo_dewey' => '757', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Otros temas', 'codigo_dewey' => '758', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Tratamiento histórico, geográfico, de personas', 'codigo_dewey' => '759', 'clasificacion_id' => 76],
                ['sub_clasificacion' => 'Procesos en relieve (impresión de planchas de madera)', 'codigo_dewey' => '761', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Procesos litográficos (planográficos)', 'codigo_dewey' => '763', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Cromolitografía y serigrafía', 'codigo_dewey' => '764', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Grabado en metal', 'codigo_dewey' => '765', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Media tinta, aguatinta, procesos relacionados', 'codigo_dewey' => '766', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Aguafuerte, grabados a punta seca', 'codigo_dewey' => '767', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Grabados', 'codigo_dewey' => '769', 'clasificacion_id' => 77],
                ['sub_clasificacion' => 'Técnicas, equipo y materiales', 'codigo_dewey' => '771', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Procesos con sales metálicas', 'codigo_dewey' => '772', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Procesos de pigmentación de la impresión', 'codigo_dewey' => '773', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Holografía', 'codigo_dewey' => '774', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Campos y clases de fotografía', 'codigo_dewey' => '778', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Fotografías', 'codigo_dewey' => '779', 'clasificacion_id' => 78],
                ['sub_clasificacion' => 'Principios generales y formas musicales', 'codigo_dewey' => '781', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Música vocal', 'codigo_dewey' => '782', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Música para voces individuales La voz', 'codigo_dewey' => '783', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Instrumentos y conjuntos instrumentales', 'codigo_dewey' => '784', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Conjuntos con un solo instrumento por parte', 'codigo_dewey' => '785', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Instrumentos de teclado y otros', 'codigo_dewey' => '786', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Instrumentos de cuerda (Cordófonos)', 'codigo_dewey' => '787', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Instrumentos de viento (Acrófonos)', 'codigo_dewey' => '788', 'clasificacion_id' => 79],
                ['sub_clasificacion' => 'Representaciones públicas', 'codigo_dewey' => '791', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Presentaciones escénicas', 'codigo_dewey' => '792', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Juegos y diversiones bajo techo', 'codigo_dewey' => '793', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Juegos de destreza bajo techo', 'codigo_dewey' => '794', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Juegos de suerte', 'codigo_dewey' => '795', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Deportes y juegos atléticos y al aire libre', 'codigo_dewey' => '796', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Deportes acuáticos y aéreos', 'codigo_dewey' => '797', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Deportes ecuestres y carreras de animales', 'codigo_dewey' => '798', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Pesca, caza, tiro', 'codigo_dewey' => '799', 'clasificacion_id' => 80],
                ['sub_clasificacion' => 'Filosofía y teoría', 'codigo_dewey' => '801', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '802', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '803', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '805', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Organizaciones y gerencia', 'codigo_dewey' => '806', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '807', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Retórica y colecciones de literatura', 'codigo_dewey' => '808', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Historia, descripción, crítica', 'codigo_dewey' => '809', 'clasificacion_id' => 81],
                ['sub_clasificacion' => 'Poesía norteamericana en inglés', 'codigo_dewey' => '811', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Teatro norteamericano en inglés', 'codigo_dewey' => '812', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Novelística norteamericana en inglés', 'codigo_dewey' => '813', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Ensayos norteamericanos en inglés', 'codigo_dewey' => '814', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Discursos norteamericanos en inglés', 'codigo_dewey' => '815', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Cartas norteamericanas en inglés', 'codigo_dewey' => '816', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Humor y sátira norteamericanos en inglés', 'codigo_dewey' => '817', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Escritos varios norteamericanos', 'codigo_dewey' => '818', 'clasificacion_id' => 82],
                ['sub_clasificacion' => 'Poesía inglesa', 'codigo_dewey' => '821', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Teatro inglés', 'codigo_dewey' => '822', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Novelística inglesa', 'codigo_dewey' => '823', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Ensayos ingleses', 'codigo_dewey' => '824', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Discursos ingleses', 'codigo_dewey' => '825', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Cartas inglesas', 'codigo_dewey' => '826', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Humor y sátira ingleses', 'codigo_dewey' => '827', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Escritos varios ingleses', 'codigo_dewey' => '828', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Literatura inglesa antigüa (anglosajona)', 'codigo_dewey' => '829', 'clasificacion_id' => 83],
                ['sub_clasificacion' => 'Poesía alemana', 'codigo_dewey' => '831', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Teatro alemán', 'codigo_dewey' => '832', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Novelística alemana', 'codigo_dewey' => '833', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Ensayos alemanes', 'codigo_dewey' => '834', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Discursos alemanes', 'codigo_dewey' => '835', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Cartas alemanas', 'codigo_dewey' => '836', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Humor y sátira alemanes', 'codigo_dewey' => '837', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Escritos varios alemanes', 'codigo_dewey' => '838', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Otras literaturas germánicas', 'codigo_dewey' => '839', 'clasificacion_id' => 84],
                ['sub_clasificacion' => 'Poesía francesa', 'codigo_dewey' => '841', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Teatro francés', 'codigo_dewey' => '842', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Novelística francesa', 'codigo_dewey' => '843', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Ensayos franceses', 'codigo_dewey' => '844', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Discursos franceses', 'codigo_dewey' => '845', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Cartas francesas', 'codigo_dewey' => '846', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Humor y sátira franceses', 'codigo_dewey' => '847', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Escritos varios franceses', 'codigo_dewey' => '848', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Literaturas provenzal y catalana', 'codigo_dewey' => '849', 'clasificacion_id' => 85],
                ['sub_clasificacion' => 'Poesía italiana', 'codigo_dewey' => '851', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Teatro italiano', 'codigo_dewey' => '852', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Novelística italiana', 'codigo_dewey' => '853', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Ensayos italianos', 'codigo_dewey' => '854', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Discursos italianos', 'codigo_dewey' => '855', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Cartas italianas', 'codigo_dewey' => '856', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Humor y sátira italianos', 'codigo_dewey' => '857', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Escritos varios italianos', 'codigo_dewey' => '858', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Literatura portuguesa', 'codigo_dewey' => '859', 'clasificacion_id' => 86],
                ['sub_clasificacion' => 'Poesía española', 'codigo_dewey' => '861', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Teatro español', 'codigo_dewey' => '862', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Novelística española', 'codigo_dewey' => '863', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Ensayos españoles', 'codigo_dewey' => '864', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Discursos españoles', 'codigo_dewey' => '865', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Cartas españolas', 'codigo_dewey' => '866', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Humor y sátira españoles', 'codigo_dewey' => '867', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Escritos varios españoles', 'codigo_dewey' => '868', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Literatura portuguesa', 'codigo_dewey' => '869', 'clasificacion_id' => 87],
                ['sub_clasificacion' => 'Poesía latina', 'codigo_dewey' => '871', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Poesía y teatro dramáticos latinos', 'codigo_dewey' => '872', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Poesía y novelística épicas latinas', 'codigo_dewey' => '873', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Poesía lírica latina', 'codigo_dewey' => '874', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Discursos latinos', 'codigo_dewey' => '875', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Cartas latinas', 'codigo_dewey' => '876', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Humor y sátira latinos', 'codigo_dewey' => '877', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Escritos varios latinos', 'codigo_dewey' => '878', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Literaturas de otras lenguas itálicas', 'codigo_dewey' => '879', 'clasificacion_id' => 88],
                ['sub_clasificacion' => 'Poesía griega clásica', 'codigo_dewey' => '881', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Poesía y teatro dramáticos griegos clásicos', 'codigo_dewey' => '882', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Poesía y novelística épicas griegas clásicas', 'codigo_dewey' => '883', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Poesía lírica griega clásica', 'codigo_dewey' => '884', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Discursos griegos clásicos', 'codigo_dewey' => '885', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Cartas griegas clásicas', 'codigo_dewey' => '886', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Humor y sátira griegos clásicos', 'codigo_dewey' => '887', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Escritos varios griegos clásicos', 'codigo_dewey' => '888', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Literatura griega moderna', 'codigo_dewey' => '889', 'clasificacion_id' => 89],
                ['sub_clasificacion' => 'Indoeuropeas, orientales y célticas', 'codigo_dewey' => '891', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Afroasiáticas. Semíticas', 'codigo_dewey' => '892', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Afroasiáticas no semíticas', 'codigo_dewey' => '893', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Altaicas, urálicas, hiperbóleas, dravídicas', 'codigo_dewey' => '894', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Del Asia oriental y sudoriental', 'codigo_dewey' => '895', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Africanas', 'codigo_dewey' => '896', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Nativas norteamericanas', 'codigo_dewey' => '897', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Nativas sudamericanas', 'codigo_dewey' => '898', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Austronesias y otras', 'codigo_dewey' => '899', 'clasificacion_id' => 90],
                ['sub_clasificacion' => 'Filosofía y teoría', 'codigo_dewey' => '901', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Miscelánea', 'codigo_dewey' => '902', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Diccionarios y enciclopedias', 'codigo_dewey' => '903', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Relatos colectivos de acontecimientos', 'codigo_dewey' => '904', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Publicaciones seriadas', 'codigo_dewey' => '905', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Organizaciones y gerencia', 'codigo_dewey' => '906', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Educación, investigación, temas relacionados', 'codigo_dewey' => '907', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Tratamiento de clases de personas', 'codigo_dewey' => '908', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Historia universal', 'codigo_dewey' => '909', 'clasificacion_id' => 91],
                ['sub_clasificacion' => 'Geografía histórica', 'codigo_dewey' => '911', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Representaciones gráficas', 'codigo_dewey' => '912', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en el mundo antiguo', 'codigo_dewey' => '913', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en Europa', 'codigo_dewey' => '914', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en Asia', 'codigo_dewey' => '915', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en África', 'codigo_dewey' => '916', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en América del Norte', 'codigo_dewey' => '917', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en América del Sur', 'codigo_dewey' => '918', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Geografía de y viajes en otras áreas', 'codigo_dewey' => '919', 'clasificacion_id' => 92],
                ['sub_clasificacion' => 'Biografía, nombres, insignias', 'codigo_dewey' => '929', 'clasificacion_id' => 93],
                ['sub_clasificacion' => 'China hasta 420', 'codigo_dewey' => '931', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Egipto hasta 640', 'codigo_dewey' => '932', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Palestina hasta 70', 'codigo_dewey' => '933', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'India hasta 647', 'codigo_dewey' => '934', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Mesopotamia y Meseta Iraní hasta 637', 'codigo_dewey' => '935', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Europa al norte y al occidente de Italia hasta ca. 499', 'codigo_dewey' => '936', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Italia y territorios adyacentes hasta 476', 'codigo_dewey' => '937', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Grecia hasta 323', 'codigo_dewey' => '938', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Otras partes del mundo antiguo hasta 640', 'codigo_dewey' => '939', 'clasificacion_id' => 94],
                ['sub_clasificacion' => 'Islas Británicas', 'codigo_dewey' => '941', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Inglaterra y Gales', 'codigo_dewey' => '942', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Europa central. Alemania', 'codigo_dewey' => '943', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Francia y Mónaco', 'codigo_dewey' => '944', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Península Itálica e islas adyacentes', 'codigo_dewey' => '945', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Península Ibérica e islas adyacentes', 'codigo_dewey' => '946', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Europa Oriental. Rusia', 'codigo_dewey' => '947', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Escandinavia', 'codigo_dewey' => '948', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'Otras partes de Europa', 'codigo_dewey' => '949', 'clasificacion_id' => 95],
                ['sub_clasificacion' => 'China y áreas adyacentes', 'codigo_dewey' => '951', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Japón', 'codigo_dewey' => '952', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Península de Arabia y áreas adyacentes', 'codigo_dewey' => '953', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Asia del Sur. India', 'codigo_dewey' => '954', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Irán', 'codigo_dewey' => '955', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Medio Oriente (Cercano Oriente)', 'codigo_dewey' => '956', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Siberia (Rusia asiática)', 'codigo_dewey' => '957', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Asia Central', 'codigo_dewey' => '958', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Asia Sudoriental', 'codigo_dewey' => '959', 'clasificacion_id' => 96],
                ['sub_clasificacion' => 'Túnez y Libia', 'codigo_dewey' => '961', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Egipto y Sudán', 'codigo_dewey' => '962', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Etiopía y Eritrea', 'codigo_dewey' => '963', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Costa noroccidental africana e islas cercanas', 'codigo_dewey' => '964', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Argelia', 'codigo_dewey' => '965', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'África occidental e islas cercanas', 'codigo_dewey' => '966', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'África central e islas cercanas', 'codigo_dewey' => '967', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'África del Sur. República de Sudáfrica', 'codigo_dewey' => '968', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Islas del Oceáno Índico Sur', 'codigo_dewey' => '969', 'clasificacion_id' => 97],
                ['sub_clasificacion' => 'Canadá', 'codigo_dewey' => '971', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Mesoamérica (América Media) México', 'codigo_dewey' => '972', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Estados Unidos', 'codigo_dewey' => '973', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Nororiente de Estados Unidos', 'codigo_dewey' => '974', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Sudoriente de Estados Unidos', 'codigo_dewey' => '975', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Centro-sur de Estados Unidos', 'codigo_dewey' => '976', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Centro-norte de Estados Unidos', 'codigo_dewey' => '977', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Occidente de Estados Unidos', 'codigo_dewey' => '978', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Región de la Gran Cuenca y de la Vertiente del Pacífico', 'codigo_dewey' => '979', 'clasificacion_id' => 98],
                ['sub_clasificacion' => 'Brasil', 'codigo_dewey' => '981', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Argentina', 'codigo_dewey' => '982', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Chile', 'codigo_dewey' => '983', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Bolivia', 'codigo_dewey' => '984', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Perú', 'codigo_dewey' => '985', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Colombia y Ecuador', 'codigo_dewey' => '986', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Venezuela', 'codigo_dewey' => '987', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Guayanas', 'codigo_dewey' => '988', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Paraguay y Uruguay', 'codigo_dewey' => '989', 'clasificacion_id' => 99],
                ['sub_clasificacion' => 'Nueva Zelanda', 'codigo_dewey' => '993', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Australia', 'codigo_dewey' => '994', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Melanesia. Nueva Guinea', 'codigo_dewey' => '995', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Otras partes del Océano Pacífico Polinesia', 'codigo_dewey' => '996', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Islas del Océano Atlántico', 'codigo_dewey' => '997', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Islas árticas y Antártida', 'codigo_dewey' => '998', 'clasificacion_id' => 100],
                ['sub_clasificacion' => 'Mundos extraterrestres', 'codigo_dewey' => '999', 'clasificacion_id' => 100]
            ]
        );
    }
}
